# Generated by Django 5.2.10 on 2026-01-12 09:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('name', models.CharField(db_index=True, help_text="Keyword name (e.g., 'copper', 'China', 'mining')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the keyword', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetalNews',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('title', models.CharField(db_index=True, help_text='Article title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Article description or summary')),
                ('url', models.URLField(help_text='Article URL (unique to prevent duplicates)', max_length=1000, unique=True)),
                ('source', models.CharField(db_index=True, help_text='News source name', max_length=200)),
                ('published_at', models.DateTimeField(db_index=True, help_text='Article publication timestamp')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector for PostgreSQL search', null=True)),
            ],
            options={
                'verbose_name': 'Metal News',
                'verbose_name_plural': 'Metal News',
                'db_table': 'metal_news',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('keyword_type', models.CharField(choices=[('topic', 'Topic'), ('country', 'Country'), ('related_metal', 'Related Metal'), ('industry', 'Industry'), ('company', 'Company'), ('region', 'Region'), ('other', 'Other')], db_index=True, default='other', help_text='Type/category of the keyword', max_length=20)),
                ('keyword', models.ForeignKey(help_text='Keyword', on_delete=django.db.models.deletion.CASCADE, related_name='news_keywords', to='metal_news.keyword')),
                ('news', models.ForeignKey(help_text='News article', on_delete=django.db.models.deletion.CASCADE, related_name='news_keywords', to='metal_news.metalnews')),
            ],
            options={
                'verbose_name': 'News Keyword',
                'verbose_name_plural': 'News Keywords',
                'db_table': 'news_keywords',
                'ordering': ['keyword_type', 'keyword__name'],
            },
        ),
        migrations.AddField(
            model_name='metalnews',
            name='keywords',
            field=models.ManyToManyField(help_text='Keywords associated with this news article', related_name='news_articles', through='metal_news.NewsKeyword', to='metal_news.keyword'),
        ),
        migrations.AddIndex(
            model_name='newskeyword',
            index=models.Index(fields=['news', 'keyword_type'], name='news_keywor_news_id_6b14fd_idx'),
        ),
        migrations.AddIndex(
            model_name='newskeyword',
            index=models.Index(fields=['keyword', 'keyword_type'], name='news_keywor_keyword_2c9350_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newskeyword',
            unique_together={('news', 'keyword', 'keyword_type')},
        ),
        migrations.AddIndex(
            model_name='metalnews',
            index=models.Index(fields=['source'], name='metal_news_source_002a96_idx'),
        ),
        migrations.AddIndex(
            model_name='metalnews',
            index=models.Index(fields=['-published_at'], name='metal_news_publish_170333_idx'),
        ),
        migrations.AddIndex(
            model_name='metalnews',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='metal_news_search__bec611_gin'),
        ),
        migrations.AddConstraint(
            model_name='metalnews',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_news_url'),
        ),
    ]
