# Generated by Django 5.2.10 on 2026-01-08 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('symbol', models.CharField(db_index=True, help_text='Metal identifier/symbol', max_length=50)),
                ('name', models.CharField(help_text='Metal display name', max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=10, help_text='Latest normalized price value', max_digits=20)),
                ('unit', models.CharField(default='normalized', help_text='Price unit type', max_length=50)),
                ('indicator_one', models.DecimalField(blank=True, decimal_places=10, help_text='First indicator value', max_digits=20, null=True)),
                ('indicator_two', models.DecimalField(blank=True, decimal_places=10, help_text='Second indicator value', max_digits=20, null=True)),
                ('indicator_three', models.DecimalField(blank=True, decimal_places=10, help_text='Third indicator value', max_digits=20, null=True)),
                ('chart_indicator', models.DecimalField(blank=True, decimal_places=10, help_text='Chart indicator value', max_digits=20, null=True)),
                ('last_date', models.DateTimeField(blank=True, help_text='Last date from external API', null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, help_text='Timestamp when data was fetched from API')),
                ('price_history', models.JSONField(blank=True, help_text='Historical price data as JSON array', null=True)),
            ],
            options={
                'verbose_name': 'Metal Price',
                'verbose_name_plural': 'Metal Prices',
                'db_table': 'metal_prices',
                'ordering': ['-fetched_at', 'symbol'],
                'indexes': [models.Index(fields=['symbol'], name='metal_price_symbol_3af079_idx'), models.Index(fields=['-fetched_at'], name='metal_price_fetched_1995b9_idx')],
            },
        ),
    ]
